### ISSUE TITLE
nbSPI do not work on esp8266 arduino sdk 3.0.1 and 3.1.2 

### ISSUE THREAD

**Issue by DengJackNo1** [ESPboy-edu/ESPboy_GameBoy#3]
hello,bro,i am diy my espboy, When I was compiling the Arduino project, I found that nbSPI was not working.
gpio16 as reverse tft cs pin, when high level .cs pin is active.
gpio 12(the spi miso pin) as tft dc pin .high level as tft display data , low level as tft display data. i do not konw  the reason.
maybe:
1. gpio 12 is spi miso pin,so nbspi do not work
2.nbspi spi speed is too fast
I hope to receive your assistance.
Here is my test code

```cpp

// TFT_eSPI setup ST7735
#define TFT_MISO  PIN_D6  // D6 not connect,Automatically assigned with ESP8266 if not defined
#define TFT_MOSI  PIN_D7  // Automatically assigned with ESP8266 if not defined
#define TFT_SCLK  PIN_D5  // Automatically assigned with ESP8266 if not defined

//#define TFT_CS    -1  // Chip select control pin D8
#define TFT_DC    12  // Data Command control pin
#define TFT_RST   -1 

// nbspi setup
// Set an IO to measure timing
#define NBSPI_TDBG_IO 12
#define NBSPI_TDBG_HIGH GPOS = (1<<NBSPI_TDBG_IO) // 0.1 ?s
#define NBSPI_TDBG_LOW GPOC = (1<<NBSPI_TDBG_IO) // 0.1 ?s

#include <TFT_eSPI.h>
#include <SPI.h>
#include "nbSPI.h"
TFT_eSPI tft;
extern SPIClass spi;
uint8_t sBuffer[50][50];
void setup() {
  int i;
  Serial.begin(115200);
  Serial.println("hello 1");
  pinMode(16, OUTPUT);  // select
  digitalWrite(16, 1);  // cs active
  tft.begin();
  tft.fillScreen(TFT_RED);
  delay(1000);
  memset(sBuffer, 0xff, 2500);
  tft.setAddrWindow(10, 10, 50, 50);
  NBSPI_TDBG_HIGH;
  spi.transfer((uint8_t *)sBuffer, 2500);
  NBSPI_TDBG_LOW;
  memset(sBuffer, 0, 2500);
  while (nbSPI_isBusy())
    ;
  Serial.println("hello 1");
  NBSPI_TDBG_HIGH;
  //spi.transfer((uint8_t *)sBuffer, 2500);
  nbSPI_writeBytes((uint8_t *)sBuffer, 1600);
  NBSPI_TDBG_LOW;
  Serial.println("hello 2");
  while (nbSPI_isBusy()) {
    delayMicroseconds(2);
  };
  Serial.println("hello end3");
}

void loop() {
  delay(1000);
  // put your main code here, to run repeatedly:
}

**Comment by ESPboy-edu** [comment]
Hello.

Are you using the standard ESPboy circuit?
https://www.instructables.com/ESPboy-DIY-Retro-Gaming-and-Software-Development-M/

Because the standard ESPboy
GPIO12 (D6) is not used
GPIO16 (D0) is used for DC display
CS display is controlled by MCP23017

I would like to point out that if you use the standard ESPboy circuit and the recommended components (in particular the display model), then nbSPI should work fine.
If you have changed the schematic, it is no longer ESPboy and there may be problems that need to be dealt with separately.

**Comment by DengJackNo1** [comment]
hi,Thank you for your reply.
yes,I didn't use MCP23017.Just consider it as a game console.
so i changed the schematic.

gpio 16 14 13 12 as tft spi pin
spiflash use dout mode  to frree up gpio 9,10.
other pin 0 1 2 3 4 9 10 15 as button pins
io5 as buzzer pin,not use rgb led
I have a idea , because i use 160x128 tft,so i can use (160-128) X 128 range as virtual RGB LED.
or 14 13 12 as tft pin,cs pin is gnd.
other pin 0 1 2 3 16 9 10 15 as button pins
and pin 4 is led,pin 5 is buzzer

fortunately , i can use nbspi work on my diy espboy by change the nbSPI.h.
I Deleted " "NBSPI_TDBG_HIGH NBSPI_TDBG_LOW" in  the function void nbSPI_writeBytes() and void nbSPI_ISR();
instead of
  while (nbSPI_isBusy());
  NBSPI_TDBG_HIGH;
  nbSPI_writeBytes((uint8_t *)sBuffer, size);
  while (nbSPI_isBusy());  //  maybe delete to improve performance in espboy arduboy2 lib
  NBSPI_TDBG_LOW;
it work well.
I think this will be helpful.

**Comment by ESPboy-edu** [comment]
ESPboy is not a game console ) You can read more at www.espboy.com.

You have built a device of your own design and it is not an ESPboy. 

That's why ESPboy has official circuitry, official modules and software and support. I spent many months to debug hardware and software to make everything work more or less stably.

Of course anyone can build any device they want, but debugging will take a long time.

I can advise you to build a real ESPboy and I will help you in this case if necessary.

As far as I can see you've completely broken the nbSPI library. maybe something works, but definitely not the way it should.

**Comment by ESPboy-edu** [comment]
Not related to the ESPboy project
